### ISSUE TITLE
Breaking change in 0.17.1 patch release

### ISSUE THREAD

**Issue by ricochet** [bytecodealliance/wit-bindgen#839]
With transitive deps on wasm-tools crates, we bumped into a breaking from `wit-parser`. 

Our Cargo.toml had:
```toml
wit-parser = "0.13"
wit-component = "0.20"
wit-bindgen-core = "0.17"
```
When wit-bindgen-core updated wit-parser and wit-component minor versions, it has to be a minor bump to wit-bindgen-core to avoid this going forward.

https://crates.io/crates/wit-bindgen-core/0.17.0/dependencies
https://crates.io/crates/wit-bindgen-core/0.17.1/dependencies
