### ISSUE TITLE
`v0.19.1` Link-time Optimization (LTO) produces cabi error

### ISSUE THREAD

**Issue by DougAnderson444** [bytecodealliance/wit-bindgen#864]
using `wit-bindgen` version `0.19.1`, when I: 

`cargo component build --release` 

with 

```toml
[profile.release]
lto = "fat" # anything other than false
```

I get the error:

```sh
error: module does not export a function named `cabi_realloc`
```

Note that this did not happen with `v0.16.0` it was optimizing for release without error.
